### ISSUE TITLE
logR without explicitely using logR at each statement

### ISSUE THREAD

**Issue by jwijffels** [jangorecki/logR#3]
Interesting package, I'm considering to use this as a replacement of some custom logging functionality.

A question though. What I would be interested in is using logR without expliticity having to call logR at each R statement. 
Hence my question. What would be needed/changed/hacked into such that the usage of logR would just require setting the database options at the start and next that every top-level R expression/function which is used is logged to the database as well as possible error or warning messages?

**Comment by jangorecki** [comment]
Just keep in mind I'm dropping `dwtools` dependency and moving to DBI databases only. The `DBI_only` branch is the latest version now.

Regarding your question, hack evaluate in global environment sounds too tricky for me. You may get good answer on SO, MrFlick is good at that stuff.
A simplest workaround could be piping, e.g. `my_process() %>% logR`, more or less the same as `logR(my_process())` but maybe easier to add to code. All logR extra params can be setup using `options`.

If you would have only a range of functions you want to log then you can try the approach I used for logging data.table queries `[.data.table` in [dtq](https://github.com/jangorecki/dtq) package.

**Comment by jwijffels** [comment]
Thanks. Asked it at stackoverflow: http://stackoverflow.com/questions/30241412/get-all-r-code-which-is-run-when-running
